freifunk-berlin/firmware

- feeds.conf
Update feed of freifunk-berlin/firmware-packages with fixes of
vpn03-related firewall rules. This should also fix a malfunctioning
olsr, see error messages in #171 and #192.
> [feeds] update feeds to include vpn03-firewall fix

- packages/vpn.txt
At the moment users can't change firewall settings without using a shell. This
adds the `luci-app-firewall` package to empower people without shell knowledge to
change firewall settings on their own.
> [packages] add luci-app-firewall

- Makefile
The build isn't cleaned up when we add patches to target/linux/ar71xx/patches
> [Makefile]: remove build_dir/target-* when cleaning up

- Makefile
In some cases the imagebuilder can fail on some profiles but
doesn't report back the fail to make. Fix #228.
> [Makefile] fix fail of imagebuilder doesn't fail the build

- configs/ar71xx.config
- configs/ar71xx_mikrotik.config
- configs/mpc85xx.config
- configs/x86.config
Requested in http://lists.berlin.freifunk.net/pipermail/berlin/2015-April/027818.html . Tested with a 4300. Works.
> configs/ar71xx: build ath9k-htc module

- config.mk
Changelog:
229d60f BB: openssl: update to v1.0.2a (14 CVEs)
64ae631 kernel: remove the netfilter optimization that skips the filter table, it has caused too many issues
8737792 ath9k: fix a beacon enable handling bug
12c281e ar71xx: Fix LED polarity for the TP-LINK TL-MR13U.
26093e7 Backport: ar71xx: Fix board detection for the TP-LINK TL-MR13U.
878af31 BB: ubox: fix segmentation fault in insmod
11fa76d BB: fstools: fix build with enabled ubifs extroot support
8d49c6d BB: fstools: cumulative backport
dfcbb35 BB: ubox: kmodloader: support loading kmods from multiple directories
e0b8c83 samba36: update to 3.6.25, fixes remote code execution bug (CVE-2015-0240)
edefd1a BB: build: improve feed handling for opkg.conf
4ae7fc3 BB:ramips:Kingston MLW221 cleanup
e602c6d openssl: fix upstream …
> config.mk: update barrierbreaker rev

- Makefile
Doesn't show any version atm on master. I'm not sure why? But when creating an annotated and signed  tag it works.
We should first add a tag on the merge commit or before merging this.
> [Makefile] describe version

- Makefile
Reverts freifunk-berlin/firmware#267
@lynxis , why did you merge this without further discussion? For master(-based) build this effectively sets the version to "15.05" now, breaking firmware filenames and migration. People who update to one of these firmwares will permanently break migration, see last lines of https://github.com/freifunk-berlin/firmware-packages/blob/master/utils/freifunk-berlin-migration/uci-defaults/999_freifunk-berlin-migration.sh .
> Revert: "[Makefile] describe version" (breaks filenames and migration)

- feeds.conf
Included changes:
8a70dde unzip: patch CVE-2015-7696, CVE-2015-7697 and integer underflow
f8a70fc madplay: some build variant related fixes
6f8928a node: disable MIPS16
375b9ae python: fix two build depend issues
ffd3b19 gnutls: update to 3.4.6
f690a75 node-cylon: dont double build firmata and serialport
25a4a2f libupm: add fixes for 2 sensors
fbef79f swig: make it compile even if pcre libs are not available
3740ab8 node: add a python/host dependency
5d079de zabbix: enable IPv6 support
c86d2d5 swig: add PKG_LICENSE_FILE
56e6a67 node-hid: set proper version and revision
a0baae4 node-hid: set proper version and revision
02d6846 node-cylon: add proper download path and set version properly
8133570 node-arduino-firmata: set proper download path and set version properly
0c2c464 madplay: add …
> [feeds] update packages feed to HEAD of release branch 15.05/CC

- Makefile
this adds following to VERSION.txt
- Repository-URL of Feed
- Branch-name of Feed
- Commit-hash of Feed
also have commit-hash of firmware in resulting filenames and insode build image
detection of Release-version and not including commmit-hash will be done later
@sarumpaet 
results can be seen http://buildbot.berlin.freifunk.net/builders/ramips/builds/72
> improve version-file and build-hash into filename

- feeds.conf
includes:
- oonf 0.11.2
- move to Github-repository of olsr.org
- fix for olsrd smartgateway syntax
this also mainly fixes the build fails, as of moved OLSR-repo-location
> fix: update feed routing to master/05fa82f

- packages/default_4MB.sh
- packages/default_4MB.txt
- patches/016-imagebuilder-custom-postinst-script.patch
remove all opkg-related stuff from these small devices in order to gain some memory
-  this brings something around 120kB 
- and it's veeeery unlikely that the owner of a 4MB-router will do anything more than just default Freifunk
> more space on 4MB flash

- packages/default_4MB.sh
this is a improved version of the 4MB-workaround to remove opkg (https://github.com/freifunk-berlin/firmware/pull/341)
- tested it on a 4MB unit
- please check and merge
> remove opkg on 4MB devices - improved

- Makefile
When including first the common.config the target config can override certain symbols
if needed. Make a target more flexible.
> Makefile: include common.config before $(TARGET).config

- patches/700-banner-info.patch
This removes the need to release a new firmware when the meeting-location
changes and gives a central place to announce this.
> patches: reference official webpage to check of weekly meetings

- patches/703-policyrouting_fix_bypass-vpn.patch
- patches/series
this fixes #402 
by preventing execution of "etc/hotplug.d/iface/30-policyrouting" for interface WAN
> policyrouting - fix for bypassing VPN for client on meshed router

- Makefile
Remove variables that will not be used anywhere. Not sure if they have been used once, but currently they are unused.
Is it ok to remove them?
when ok, just rebase onto master.
> Remove unused vars in Makefile

- Makefile
add new target "images" which only builds our firmwareimages with the Imagebuilder just created
and places them in the final-folder (FW_TARGET_DIR).
This is a prerequisite of final rule "firmwares", which only will add the Imagebuilder, SDK, Toolchain and packages into the final-folder.
code posses build: https://buildbot.berlin.freifunk.net/builders/mpc85xx-generic/builds/191
> further cleanup of Makefile

- Makefile
move imagebuilder, sdk, toolchain to final folder to save some space in BUILD_DIR (see issue #414)
I don't see any problem in merging this. Or is there any use of these files in the BUILD_DIR?
> move finalfiles instead of copy

- Makefile
- README.md
a commandline will look like:
make images IB_FILE=<file> TARGET=... PACKAGES_LIST_DEFAULT=fancy-image
and everyone can build a final image for the own needs. I use this to build specialized images for the UBNT-ERX.
The resulting image will also use the .ipks stored on buildbot without signing issues as a self compiled image would have.
> Build images from imagebuilder

- configs/common.config
The nf-nathelper-extra kernel module enables proper network address
translation for protocols such as pptp, gre, sip.
Package description:
https://lede-project.org/packages/pkgdata/kmod-nf-nathelper-extra
> configs: build kmod-nf-nathelper-extra as module

- packages/backbone.txt
- packages/default.txt
To enable HTTPS again on the default and backbone image for 8MB routers
we have to add the libustream-mbedtls package to the package set for the
imagebuilder.  Otherwise the init script can not find the library and
will not create the certs and keys for uhttpd:
https://github.com/lede-project/source/blob/master/package/network/services/uhttpd/files/uhttpd.init#L155
Fix for issue:
https://github.com/freifunk-berlin/firmware/issues/446
We still have to fix the configuration for the certificate. Seems like the configuration creates a certificate but maybe with values we don't like or specified. We should fix our uci-default script for uhttpd in another commit.
> packages: add libustream-mbedtls to default and backbone package set

- Makefile
- configs/ramips-mt7621.config
- patches/000-add_ubnt-erx-sfp.patch
- patches/series
- profiles/ramips-mt7621.profiles
this patch adds a "cheap" backport of the Ubiquiti ERX-SFT support from LEDE-master to LEDE-17.01. So this patch adds the board "ubnt-erx-sfp" for ramips-mt7621 target.
I call it cheap, because it's not using common parts in a included DTS, just a copy of the ERX-dts modded for ERX-SFP.
also the GPIOs are not working as in Master.
> backport Ubiquiti ERX SFP to LEDE 17.01

- patches/202-luci_fix_display_of_disabled_aps.patch
- patches/series
Display correct values for SSID and Mode of disabled wireless APs as discussed in Issue https://github.com/freifunk-berlin/firmware/issues/501
> Torte 1.0.0 rc1: Display of disabled APs

- Makefile
- config.mk
An approach to fix https://github.com/freifunk-berlin/firmware/issues/414 by adding an option to config.mk (SET_BUILDBOT) for handling the "IS_BUILDBOT" env of https://github.com/freifunk-berlin/buildbot/pull/42
> Reduce disc-space usage on buildbots

- patches/800-mbedtls-accept-rsa-1024.patch
- patches/series
Patch mbedtls to allow 1024 bits RSA
for bbb-vpn and VPN03 compatibility
fixes https://github.com/freifunk-berlin/firmware/issues/489
> patches: patch mbedtls to allow 1024 bits RSA

- patches/001-mac80211_mesh_no_fwding_by_default.patch
- patches/201-wifi_no_meshfwding_by_default.patch
- patches/series
By default a node must have the internal 802.11s forwarding disabled,to not interfer with the mesh-routing protocols on top.
This is done by patching the kernel-default. Also update the LuCI-frontend to stay in sync.
This was tested with OpenWrt-master, and as the patches apply to OpenWrt-18.06 too, it will work also.
> disable 802.11s mesh_forwarding by default

- README.md
The wiki we referenced is in read-only mode and will cease to exist in
the future. I update the links to point to the new openwrt
documentation.
Fixes https://github.com/freifunk-berlin/firmware/issues/597
> README: update links to point to new openwrt wiki

- Makefile
The openwrt files fetched via "git" already need the correct
permissions.
https://github.com/openwrt/luci/issues/1521
https://github.com/freifunk-berlin/firmware/issues/431
> Set "umask 022" for "git clone" and "feed update"

- CHANGELOG.md
- README.md
this updates the Readme and Changelog for the Hedy-1.0.2 release.
Did I miss something?
Finally this should be squashed into one single commit
> Hedy 1.0.2 update docs

- README.md
As the Wiki is more up to date in this regard, just put a link in the Readme.
This also shortes the Readme a bit and helps to keep a focus on the relevant facts of the buils-system / firmware
> README: link to the wiki-page for enduser relevant informations

- .github/ISSUE_TEMPLATE/bug_report.md
such a template might help the reporter to provide as much helpful information as possible.
you can see how it looks like in my personal fork of the repo.
> add a Template for bugreports

- config.mk
The OpenVPN uplink  servers are no longer going to be supported.  This was
announced on the mailing list:
https://lists.berlin.freifunk.net/pipermail/berlin/2019-March/039247.html
Removing the OpenVPN images was requested on the freifunk-berlin mailing list:
https://lists.berlin.freifunk.net/pipermail/berlin/2019-March/039302.html
> config.mk: drop openvpn images

- profiles/ar71xx-generic.profiles
Add support for the Archer c7 V5 to 18.x based firmwares
> profiles: add device archer c7 v5

- README.md
We created a Github-team (@freifunk-berlin/firmware) for the firmware-group, so we add this to the contact-section.
> ReadMe: add contact-info to the github-team

- .gitignore
- README.md
- profiles/ar71xx-generic.profiles
- profiles/ramips-mt7620.profiles
This fixes should be just rebased onto.
The removed boards are evaluation-boards, so they will not be used by end-users anyway.
> Misc fixes without functional change for enduser

- profiles/ar71xx-generic.profiles
- profiles/ath79-generic.profiles
These boards are supported on ath79 since April 2019.  So I don't expect any problems hardware-wise.
> add support for TPlink CPE v2,v3 for ath79

- .github/workflows/pr-conflicts.yml
Adds an GithubAction that checks if any open PR can not be merged on master
branch after a new commit was made to the master branch. If such conflict
will be detected, the affected PR will get the label "has conflicts". If
during a following run a conflicting PR becomes mergable, the flag will be
removed again.
This action is based on https://github.com/marketplace/actions/auto-label-merge-conflicts
This requires the correct label "has conflicts" needs to be created or the actions config must be adapted.
> GHA/pr-conflict: add workflow to automatically find conflicting PRs

- profiles/ar71xx-generic.profiles
The XW-boards are 8/64MB and should be able to run the regular packageflavor. The XM-boards are 8/32MB which makes them "tiny".
The TPLink WR710 boards are 8/32MB and should be treated as tiny.
> don't use tiny-images for Ubiquiti XW boards

- Makefile
- scripts/create_version-txt.sh
Since we apply the patches on the external repos, instead of just patching the upstream repo (e81f410) our VERSION.txt file shows this applied patch as commit of the repo. But the intention of the file is to show the original upstream commit we base on. So we need to use the "base" branch created by the patch.sh script.
broken VERSION.txt
```
https://github.com/freifunk-berlin/firmware
https://wiki.freifunk.net/Berlin:Firmware
Firmware: git branch "upstream-1907", revision 1307085
OpenWRT: repository from , git branch "", revision be248878cd
Feed packages: repository from , git branch "patched", revision 2e01dd838
Feed luci: repository from , git branch "patched", revision 79b792ba2
Feed freifunk: repository from , git branch "patched", revision 734d5a247
Feed routing: repository from , …
```
> Fix version file

- .github/workflows/build-firmware.yml
- Makefile
- Makefile.autobuild
- config.mk
- configs/common-autobuild.config
Based on #804 I evaluated several CI-solutions (https://github.com/freifunk-berlin/firmware/wiki/Continuous-integration). Based on the lack of managing such a system ourself, I effectively tested TravisCI and GitHubActions. This is my suggestion to reenable CI, with the option of CD and probably CT (fingers crossed).
I use this Github-Workflow on my repo since some months without issues. This PR implements the idea of Pr #796 in order to reduce the regular Makefile and use a specific Makefile for CI (this infact includes / reuses parts of the regular Makefile). The workflow currently just creates the imagebuilder and keeps relevant artifacts on GitHub only, but can be extended to also provide the final images.
> Enable GithubActions to automatically build the firmware / Imagebuilder

- .github/workflows/build-firmware.yml
looking at github actions logs, there are (security vulnerability) warnings:
> The set-env command is deprecated and will be disabled soon. Please upgrade to using Environment Files.
> For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
according to kubernetes/minikube#9541 running the following command to fix it:
`find . -type f -name "*.yml" -print0 | xargs -0 sed -i -r 's/echo "::set-env name=(.*)::(.*)"/echo "\1=\2" >> $GITHUB_ENV/g'"` 
---
The warnings have become errors recently, so the build fails and the fix need to be implemented. Tested this in my personal repo before and it seems fine.
> GHA/build-fw: replace deprecated 'set-env' with Environment Files

- configs/ath79-generic.config
- configs/ath79-nand.config
- configs/ipq40xx-generic.config
- configs/ramips-mt7621.config
- packagelists/profile-packages.txt
- scripts/assemble_firmware.sh
This extends the `assemble_firmware.sh` script in a way to parse a additional file `profile-packages.txt` which allows to specify packages that should be installed / removed on a per profile / board basis.
The code is based on the changes of @WeimarNetz with minor changes for our flavor of the `assemble_firmware.sh`. Initially it was intended to fix issue #696 around the ath10k-wave1 chips. 
Quickly it turns out that this might also fix issue #838 (additional drivers for boards with integrated xDSL-hardware) and also allows adding mass storage support (SATA, SD-Card) in default images.
> add Feature "devicepackages"
